/* gen_tables.c - host generator. Builds every table with build.c and writes
 *
 *   tables.c        C definitions, linked by solve, verify and rv32i-measure
 *   tables.s        RV32I data in .section .rodata (GNU as, LLVM)
 *   tables_ripes.s  the same data in .data, for Ripes' built-in assembler,
 *                   which knows only .text, .data and .bss
 *
 * All three come from one run of build_tables(), so they hold identical
 * bytes. Each table's FNV-1a checksum (over its bytes in little-endian RV32
 * memory) is printed in the headers so the assembly can check what it
 * loaded.
 *
 * usage: ./gen_tables tables.c tables.s tables_ripes.s
 */
#include <stdio.h>
#include <stdlib.h>

#include "build.h"

static tables_t t;

typedef struct {
    const char *name;  /* label and C identifier */
    const char *decl;  /* C declaration, matching tables.h */
    const char *shape; /* for comments */
    const char *what;
    const void *data;
    size_t rows, cols; /* rows = 1 for a 1-D table */
    int size;          /* bytes per element: 1 or 2 */
} table_t;

/* Order matters for tables.s: halfword tables first, then byte tables,
 * then the word table c4_row. Every halfword table has an even size, so
 * no padding is needed between them, and c4_row comes after c4_h because
 * Ripes resolves a label in .word only if it was defined earlier. */
static const table_t tables[] = {
    {"perm_q", "const uint16_t perm_q[3][PERMS]", "[3][5040] u16",
     "p after one quarter turn; row = face R, B, D", t.perm_q, 3, PERMS, 2},
    {"ori_q", "const uint16_t ori_q[3][ORIS]", "[3][729] u16",
     "o after one quarter turn; row = face R, B, D", t.ori_q, 3, ORIS, 2},
#if CORNER_PDB
    {"c4pos_q", "const uint16_t c4pos_q[3][C4POS]", "[3][840] u16",
     "cp after one quarter turn; row = face R, B, D", t.c4pos_q, 3, C4POS, 2},
#endif
    {"perm_h", "const uint8_t perm_h[PERMS]", "[5040] u8",
     "PDB: moves to solve the permutation alone", t.perm_h, 1, PERMS, 1},
    {"ori_h", "const uint8_t ori_h[ORIS]", "[729] u8",
     "PDB: moves to solve the twists alone", t.ori_h, 1, ORIS, 1},
#if CORNER_PDB
    {"c4tw_q", "const uint8_t c4tw_q[3][C4POS]", "[3][840] u8",
     "twist vector a quarter turn adds to co, indexed by the old cp",
     t.c4tw_q, 3, C4POS, 1},
    {"add81", "const uint8_t add81[C4ORI][ADD81_COLS]", "[81][128] u8",
     "digit-wise base-3 sum; index co*128 + v; columns 81..127 are 0",
     t.add81, C4ORI, ADD81_COLS, 1},
    {"c4_h", "const uint8_t c4_h[C4ORI][C4POS]", "[81][840] u8",
     "PDB: moves to solve the 4 tracked corners; index co*840 + cp",
     t.c4_h, C4ORI, C4POS, 1},
#endif
};
enum { NTABLES = sizeof tables / sizeof tables[0] };

static unsigned value(const table_t *tb, size_t i)
{
    return tb->size == 2 ? ((const uint16_t *) tb->data)[i]
                         : ((const uint8_t *) tb->data)[i];
}

static size_t bytes_of(const table_t *tb)
{
    return tb->rows * tb->cols * (size_t) tb->size;
}

static uint32_t checksum(const table_t *tb) /* FNV-1a, little-endian bytes */
{
    uint32_t h = 2166136261u;
    for (size_t i = 0; i < tb->rows * tb->cols; i++) {
        unsigned v = value(tb, i);
        for (int b = 0; b < tb->size; b++) {
            h ^= (v >> (8 * b)) & 0xFF;
            h *= 16777619u;
        }
    }
    return h;
}

static size_t total_bytes(void)
{
    size_t n = 0;
    for (int i = 0; i < NTABLES; i++)
        n += bytes_of(&tables[i]);
#if CORNER_PDB
    n += C4ORI * 4; /* c4_row, 32-bit pointers on RV32 */
#endif
    return n;
}

static FILE *open_out(const char *path)
{
    FILE *f = fopen(path, "w");
    if (!f) {
        perror(path);
        exit(1);
    }
    return f;
}

static void close_out(FILE *f, const char *path)
{
    if (fflush(f) || ferror(f) || fclose(f)) {
        fprintf(stderr, "%s: write failed\n", path);
        exit(1);
    }
}

static void write_c(const char *path)
{
    FILE *f = open_out(path);
    fprintf(f, "/* %s - GENERATED by gen_tables from build.c; do not edit.\n"
               " * Regenerate with `make tables`. Layout and index conventions:\n"
               " * tables.h. %zu bytes of tables on RV32.\n */\n",
            path, total_bytes());
    fprintf(f, "#include \"tables.h\"\n");
    for (int i = 0; i < NTABLES; i++) {
        const table_t *tb = &tables[i];
        fprintf(f, "\n/* %s %s: %s. FNV-1a %08x */\n%s = {\n", tb->name,
                tb->shape, tb->what, (unsigned) checksum(tb), tb->decl);
        for (size_t r = 0; r < tb->rows; r++) {
            if (tb->rows > 1)
                fprintf(f, "    {\n");
            for (size_t c = 0; c < tb->cols; c++) {
                if (c % 16 == 0)
                    fprintf(f, tb->rows > 1 ? "        " : "    ");
                fprintf(f, "%u,", value(tb, r * tb->cols + c));
                fputc(c % 16 == 15 || c + 1 == tb->cols ? '\n' : ' ', f);
            }
            if (tb->rows > 1)
                fprintf(f, "    },\n");
        }
        fprintf(f, "};\n");
    }
#if CORNER_PDB
    fprintf(f, "\n/* c4_row [81] pointers: c4_row[co] = c4_h[co], so a PDB lookup\n"
               " * is c4_row[co][cp] with no co * 840. */\n"
               "const uint8_t *const c4_row[C4ORI] = {\n");
    for (int r = 0; r < C4ORI; r++)
        fprintf(f, "%sc4_h[%d],%s", r % 8 == 0 ? "    " : "", r,
                r % 8 == 7 || r + 1 == C4ORI ? "\n" : " ");
    fprintf(f, "};\n");
#endif
    fprintf(f, "\nconst uint32_t tables_bytes = %zu;\n", total_bytes());
    close_out(f, path);
}

static void write_s(const char *path, const char *section)
{
    FILE *f = open_out(path);
    fprintf(f,
            "# %s - GENERATED by gen_tables from build.c; do not edit.\n"
            "# Regenerate with `make tables`. %zu bytes of tables.\n"
            "#\n"
            "# Coordinates (full definitions in tables.h):\n"
            "#   p  Lehmer rank of the cubie in each position, weights 720 120 24 6 2 1\n"
            "#   o  base 3 of the twists of positions 0..5, position 0 most significant\n"
            "#   cp rank of where cubies 0..3 (labels 1-4) are: digit r_k = pos[k] minus\n"
            "#      the earlier pos[j] < pos[k]; cp = r0*120 + r1*20 + r2*4 + r3\n"
            "#   co base 3 of the twists of cubies 0..3, cubie 0 most significant\n"
            "# Quarter turn of face f (0 R, 1 B, 2 D), both c4 lookups use the old cp:\n"
            "#   p = perm_q[f][p]   o = ori_q[f][o]\n"
            "#   co = add81[co][c4tw_q[f][cp]]   cp = c4pos_q[f][cp]\n"
            "# h = max(perm_h[p], ori_h[o], c4_h[co][cp]); solved when p == 0 && o == 0.\n"
            "# Row strides in bytes are given by the .equ lines below.\n"
            "#\n"
            "# .align 4 means 4 bytes in Ripes and 2^4 = 16 bytes in GNU as; either way\n"
            "# the tables start word aligned, and no table needs more.\n",
            path, total_bytes());
    fprintf(f, "\n    %s\n    .align 4\n\n", section);
    fprintf(f, "    .equ PERM_Q_ROW, %d      # bytes per face row of perm_q\n", PERMS * 2);
    fprintf(f, "    .equ ORI_Q_ROW, %d        # bytes per face row of ori_q\n", ORIS * 2);
#if CORNER_PDB
    fprintf(f, "    .equ C4POS_Q_ROW, %d      # bytes per face row of c4pos_q\n", C4POS * 2);
    fprintf(f, "    .equ C4TW_Q_ROW, %d        # bytes per face row of c4tw_q\n", C4POS);
    fprintf(f, "    .equ ADD81_ROW, %d         # bytes per row of add81: co << 7\n", ADD81_COLS);
    fprintf(f, "    .equ C4_H_ROW, %d          # bytes per row of c4_h\n", C4POS);
#endif
    for (int i = 0; i < NTABLES; i++) {
        const table_t *tb = &tables[i];
        fprintf(f, "\n# %s %s: %s\n# %zu bytes, FNV-1a %08x\n    .globl %s\n%s:\n",
                tb->name, tb->shape, tb->what, bytes_of(tb),
                (unsigned) checksum(tb), tb->name, tb->name);
        size_t n = tb->rows * tb->cols;
        const char *dir = tb->size == 2 ? ".half" : ".byte";
        for (size_t k = 0; k < n; k++) {
            if (k % 16 == 0)
                fprintf(f, "    %s ", dir);
            fprintf(f, "%u", value(tb, k));
            fputs(k % 16 == 15 || k + 1 == n ? "\n" : ",", f);
        }
    }
#if CORNER_PDB
    fprintf(f, "\n# c4_row [81] u32: c4_row[co] = address of row co of c4_h\n"
               "# (c4_h + 840*co), so a PDB lookup is c4_row[co][cp].\n"
               "    .align 4\n    .globl c4_row\nc4_row:\n");
    for (int r = 0; r < C4ORI; r++)
        fprintf(f, "    .word c4_h+%d\n", r * C4POS);
#endif
    close_out(f, path);
}

int main(int argc, char **argv)
{
    if (argc != 4) {
        fprintf(stderr, "usage: %s tables.c tables.s tables_ripes.s\n", argv[0]);
        return 2;
    }
    build_tables(&t);
    write_c(argv[1]);
    write_s(argv[2], ".section .rodata");
    write_s(argv[3], ".data");
    for (int i = 0; i < NTABLES; i++)
        printf("%-8s %6zu B  FNV-1a %08x\n", tables[i].name, bytes_of(&tables[i]),
               (unsigned) checksum(&tables[i]));
#if CORNER_PDB
    printf("%-8s %6d B  (pointers)\n", "c4_row", C4ORI * 4);
#endif
    printf("total    %6zu B of 131072\n", total_bytes());
    return 0;
}
